---
- name: "Homebrew | Install git"
  community.general.homebrew:
    name:
      - gh
      - git
      - gnupg
      - pinentry-mac
      - difftastic
      - mergiraf
    state: present

- name: "Override default GPG program"
  ansible.builtin.set_fact:
    git_gpg_program: /opt/homebrew/bin/gpg
